name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
 name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔹 Build and push API image
      - name: Build and push backend (FastAPI)
        uses: docker/build-push-action@v5
        with:
          context: ./hello-api
          file: ./hello-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:latest

      # 🔹 Build and push React image
      - name: Build and push frontend (React)
        uses: docker/build-push-action@v5
        with:
          context: ./hello-react
          file: ./hello-react/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-react:latest

      # 🔹 Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
