name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Short SHA
        id: vars
        run: echo "SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./hello-api
          file: ./hello-api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ steps.vars.outputs.SHA }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./hello-react
          file: ./hello-react/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-react:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-react:${{ steps.vars.outputs.SHA }}
